version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - docker push $REPOSITORY_URI:latest
artifacts:
  files:
    - imagedefinitions.json
